### ISSUE TITLE
Unique constraints

### ISSUE THREAD

**Issue by mgalpin01** [mgalpin01/EM3#19]
If we've implemented a unique constraint on a table (eg default sort order) , noting I added the constraint after I'd scripted the table in sergen... can you flag it in serenity so it knows the field should be unique and can get a serenity warning instead of hitting the database and getting a db exception?

**Comment by volkanceylan** [comment]
Implement display order functionality in Account Groups
Account group code should be unique

**Comment by volkanceylan** [comment]
Commits 79c1bd51d8532179fd5db16f5cb2258ef48b8567 and 192ba24f4ee24ca6d9ff0334dccc67128b58a47b

**Comment by mgalpin01** [comment]
working and closed
