### ISSUE TITLE
RedirectToLogin on no permission

### ISSUE THREAD

**Issue by sfackrell** [mgalpin01/EM3#21]
If you set up a new user and don't give them permission to the screen you have set as default (i.e. Data/Account at the moment) you get bounced back to the login screen with no feedback on the login page as to what happened - it looks like your login has failed when it hasn't.  

If possible it would be better to show a HTTP 403 if you have a cookie but don't have explicit permission  to a page.  A user could then select or browse to a different page.  

This scenario should only ever happen if there is an implementation problem as you wouldn't want to set a secure home page unless all users had at least read-only access to the page you set as home (default route).

This is linked to the pipeline and handling a ChallengeResult but I haven't looked into how to customise it in Serenity.  Ideally:

* no cookie => redirectToLogin
* valid cookie but no explicit permission to requested page => 403

**Comment by mgalpin01** [comment]
Agreed and we need a distinction between 403 on an inner panel and 403 on the whole page

**Comment by volkanceylan** [comment]
b8961e7832c71e0e26b2e7e790cdebbfc9c53357 should resolve the issue

**Comment by mgalpin01** [comment]
agreed working, closed
