### ISSUE TITLE
Refactor Code: Upgrade Serenity version

### ISSUE THREAD

**Issue by mgalpin01** [mgalpin01/EM3#9]

**Comment by mgalpin01** [comment]
Also one to confirm , should we update typescript version and have a project requirement for a specific/min version?

**Comment by volkanceylan** [comment]
Resolved with b90502c65f9f006a2756f3d4f53f025dc8b782ee

**Comment by volkanceylan** [comment]
Currently all versions of TypeScript after 2.1.5+ works. Only problem is i noticed that TypeScript 2.4.0+ has an ordering issue with input files, so the output file is different, but not sure if it will cause a problem (in an old version it did, so i opened an issue to TypeScript repo for them to use deterministic ordering and they decided to use file name ordering, but now they broken it again)

**Comment by mgalpin01** [comment]
closing, up tp date version
